import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

function HeroBanner() {
  const session = useSession();
  const isLoggedIn = !!session.data;
  const router = useRouter()

  const handleSignIn = async () => {
    try {
      await signIn('google');
    } catch (error) {
      console.error(error);
    }
  };

  const handleGenerate = async () => {
    try {
      await router.push('/generate');
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <section className="flex flex-col items-center justify-center bg-black text-white min-h-screen px-8">
      <div className="max-w-4xl text-center">
        <h1 className="text-6xl sm:text-8xl font-bold bg-clip-text">The generator for</h1>
        <h1 className="text-6xl sm:text-8xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 via-pink-500 to-orange-500">
          icons
        </h1>
        <p className="text-xl mt-10 mb-10 text-zinc-400">
          Use AI to generate icons in seconds instead of paying a designer and waiting for them to create them for you.
        </p>
        {!isLoggedIn ? (
        <button
        onClick={() => { void handleSignIn(); }}
          className="px-6 py-3 bg-gradient-to-r from-purple-400 via-pink-500 to-orange-500 rounded-lg text-xl font-semibold"
        >
          Get Started
        </button>
      ) : (
        <button
        onClick={() => { void handleGenerate(); }}
          className="px-6 py-3 bg-gradient-to-r from-purple-400 via-pink-500 to-orange-500 rounded-lg text-xl font-semibold"
        >
          Generate Icons
        </button>
      )}
      </div>
      <div className="mt-12">
        {/* <Image
          src="/banner.png"
          alt="an image of a bunch of nice looking icons"
          width="600"
          height="400"
          className="rounded-lg shadow-lg"
        /> */}
      </div>
    </section>
  );
}

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen flex-col">
        <HeroBanner />
      </main>
    </>
  );
};

export default HomePage;
